---
title: "Lab 8 test"
author: "Natalie Rossington"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(leaflet)
library(sf)
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
library(corrplot)
```

```{r}
oilspills <- read.csv("oil_spills.csv")
```
```{r}
df_loc <- oilspills %>% 
  filter(Accident.State == "TX" & Accident.Year == 2016) %>% 
  select(Latitude, Longitude, Net.Loss..Barrels.)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

oil_sf <- st_as_sf(df_loc, coords = c("longitude","latitude"), crs = 4326)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()
```


##Make a Tmap plot with the Texas state shapefile - if you need bounds, you need a shapefile
```{r}
states <- st_read(dsn = ".", layer = "states")

tex_border <- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326)

plot(tex_border)

tm_shape(tex_border) +
  tm_polygons() +
  tm_shape(oil_sf) +
  tm_dots(size = 0.3)

#Are these spatially random (CSR)? or non random?
```

##Convert the data to spatial points patterns - combination of point data dnt he bounding window
```{r}
spill_sp <- as(oil_sf, "Spatial")
spill_ppp <- as(spill_sp, "ppp") ###specific version of spatial data to do point pattern analysis
tx_sp <- as(tex_border, "Spatial")
tx_owin <- as(tx_sp, "owin")

all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)
```

